### PR TITLE
fix name function problem

### PR DESCRIPTION
**Pull request by MorganZhang100**

### CODE REVIEW

**Comment by MorganZhang100** [comment]
@maximkhatskevich Hey Maxim, there is a bug in the "name" function. It won't give you the whole name of the object. It will just give you the last part of the name. I fix it and create a PR. Please take a look. Thanks.

**Comment by mxkh72** [comment]
@MorganZhang100 why would you think it's a bug? That's implemented this way intentionally, I didn't want full long name of the action to be printed in console, that's too much. You are free to override standard output and put into console whatever you prefer when an action has been processed or rejected. Sorry, but I won't merge this.

**Comment by MorganZhang100** [comment]
The reason why I think it's a bug is:
We have this kind of code inside the Observer. 
> if ([actionName rangeOfString:@"LogOut.Succeed"].location != NSNotFound)


Now (your code) will show the actionName as "Succeed", not "xxx.LogOut.Succeed". With the actionName of "Succeed", the observer won't know which action it is. So the observer won't work properly. That's why I think it's a bug.

**Comment by mxkh72** [comment]
Oh, I forgot about this Objective-C extension and how we use `actionName` there. Okay, then I'm going to accept your fix for version 1.*

**Comment by MorganZhang100** [comment]
Thanks, fam!

**Comment by mxkh72** [comment]
@MorganZhang100 I've released new version of library that includes your fix. Don't forget to update your Podfile inside Vango-iOS project folder, make sure you integrate UniFlow like this:

`pod 'MKHUniFlow', :git => 'https://github.com/maximkhatskevich/MKHUniFlow.git', :tag => '1.1.1'`

**Comment by MorganZhang100** [comment]
Thanks! I just updated Podfile as your suggestion.

**Pull request merged**
